
// TRADE TRACKER ACTIONS 
export const FETCH_TRACKED_TRADES = 'FETCH_TRACKED_TRADES';
export const RECEIVE_TRACKED_TRADES = 'RECEIVE_TRACKED_TRADES';
export const INSERT_TRACKED_TRADE = 'INSERT_TRACKED_TRADE';
export const UPDATE_TRACKED_TRADE = 'UPDATE_TRACKED_TRADE';
export const DELETE_TRACKED_TRADE = 'DELETE_TRACKED_TRADE';

//QUALIFIER ACTIONS 
export const GRADE_QUALIFIER = 'GRADE_QUALIFIER';



